### ISSUE TITLE
Setup message chat feature - Draft 01

### ISSUE THREAD

**Issue by brunoalfred** [Jasiri-Inc/yakwetu#2]
## Task 

-  [ ]  Setup socketio client for flutter app and all tools need to establish a connection.
-  [ ]  Setup connection to the socketio server.
-  [ ]  Implementing chats windows:
      -  [ ] 1 - 1 chat rooms
      -  [ ] 1 - many rooms
-  [ ]  Bootstrap Bloc Architecture for our app.
