### ISSUE TITLE
Setup CI/CD for the app. 

### ISSUE THREAD

**Issue by brunoalfred** [Jasiri-Inc/yakwetu#3]
## Tasks Involves:
- [ ] Setup all necessary GitHub Actions to automate running of Tests and Build.
- [ ] Connect the App to codemagic or Fastlane.

## References
- [ ] [CI/CD](https://blog.codemagic.io/flutter-ui-socket/#deploying-to-cicd-for-testing) starting point
